authors/urls.py
from django.urls import path

from authors.views import logout_user, signin, registration, AuthorListView

app_name = 'authors'

urlpatterns = [
    path('', AuthorListView.as_view(), name='index'),
    path('logout', logout_user, name='logout'),
    path('login', signin, name='login'),
    path('register', registration, name='register'),
]

blog/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('posts.urls')),
    path("users/", include('authors.urls')),
    path("products/", include('product.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from .views import index, detail, delete, create, update

app_name = 'posts'

urlpatterns = [
    path('', index, name='index'),
    path('new', create, name='create'),
    path('<post_id>', detail, name='details'),
    path('<post_id>/delete', delete, name='delete'),
    path('<post_id>/edit', update, name='update'),
]

product/urls.py
# url patterns

from django.urls import path

from . import views

app_name = 'products'

urlpatterns = [
    path('', views.ProductView.as_view(), name='products'),
    path('add/', views.AddProductView.as_view(), name='add_product'),
    path('<int:pk>', views.ProductDetailsView.as_view(), name='details'),
    path('<int:pk>/edit', views.UpdateProductView.as_view(), name='update_product'),
    path('<int:pk>/delete', views.DeleteProductView.as_view(), name='delete_product'),
]

posts/models.py
from django.contrib.auth.models import User
from django.db import models

from authors.models import Author


# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    likes = models.ManyToManyField(User, related_name="likes", blank=True)
    bookmarks = models.ManyToManyField(User, related_name='bookmarks', blank=True)

    @property
    def total_likes(self):
        return self.likes.count()

    @property
    def total_bookmarks(self):
        return self.bookmarks.count()

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created_at']


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, blank=True, null=True)
    reply_to = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    likes = models.ManyToManyField(User, related_name="comment_likes", blank=True)

    def __str__(self):
        return f"{self.user.username}"

    @property
    def total_likes(self):
        return self.likes.count()

posts/views.py
from django.shortcuts import render, get_object_or_404, redirect

from authors.models import Author
from posts.models import Post


def index(request):
    posts = Post.objects.all()
    return render(request, template_name='index.html', context={
        'title': 'Home Page',
        'content': 'Welcome to the home page of our blog!',
        'posts': posts,
    })


def detail(request, post_id):

    post = get_object_or_404(Post, pk=post_id)
    return render(request, template_name='detail.html', context={
        'title': f'Post {post_id}',
        'content': post.content,
        'post': post,
    })


def delete(request, post_id):
    Post.objects.get(id=post_id).delete()
    return redirect('posts:index')


def create(request):
    title = request.POST.get('title')
    content = request.POST.get('content')
    author = Author.objects.first()
    Post.objects.create(
        title=title,
        content=content,
        author=author,
    )
    return redirect('posts:index')


def update(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.method == 'POST':
        post.title = request.POST.get('title')
        post.content = request.POST.get('content')
        post.save()
        return redirect('posts:index')
    return render(request, template_name='update.html', context={
        'title': f'Update Post {post_id}',
        'content': post.content,
        'post': post,
    })

# def random(request):
#     posts = Post.objects.filter().order_by('?')
#     return render(request, template_name='update.html', context={
#         'title': f'Update Post {post_id}',
#         'content': post.content,
#         'post': post,
#     })

templates/commons/footer.html
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/js/bootstrap.bundle.min.js" integrity="sha384-k6d4wzSIapyDyv1kpU366/PK5hCdSbCRGRCMv+eplOQJWyd1fbcAu9OCUj5zNLiq" crossorigin="anonymous"></script>
</body>
</html>

<!-- Include JS here -->
{% block script %}
{% endblock script %}

templates/commons/header.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %} Welcome to the Authors App {% endblock %}
    </title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-SgOJa3DmI69IUzQ2PVdRZhwQ+dy64/BUtbMJw1MZ8t5HZApcHrRKUc4W0kG879m7" crossorigin="anonymous">
</head>
<body class="container my-2">

<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'posts:index' %}">Blog</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarScroll">
            <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'authors:index' %}">Authors</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'products:products' %}">Products</a>
                </li>

{#                <li class="nav-item dropdown">#}
{#                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">#}
{#                        Link#}
{#                    </a>#}
{#                    <ul class="dropdown-menu">#}
{#                        <li><a class="dropdown-item" href="#">Action</a></li>#}
{#                        <li><a class="dropdown-item" href="#">Another action</a></li>#}
{#                        <li><hr class="dropdown-divider"></li>#}
{#                        <li><a class="dropdown-item" href="#">Something else here</a></li>#}
{#                    </ul>#}
{#                </li>#}
{#                <li class="nav-item">#}
{#                    <a class="nav-link disabled" aria-disabled="true">Link</a>#}
{#                </li>#}
            </ul>
            <div class="d-inline-flex gap-3 align-items-center " role="search">
                {% if user.is_authenticated %}
                    <h5>Hi, {{ user.username|capfirst }}</h5>
                    <a href="{% url 'authors:logout' %}" class="btn btn-primary">Logout</a>
                {% else %}
                    <a href="{% url 'authors:login' %}" class=" text-decoration-none">Login</a>
                    <a href="{% url 'authors:register' %}" class="btn btn-primary">Get Started</a>
                {% endif %}
            </div>
        </div>
    </div>
</nav>

{% if messages %}
        {% for message in messages %}
            {% if forloop.first %}
                <div class="alert my-1 alert-{% if message.tags %}{{ message.tags }} {% endif %} alert-dismissible fade show" role="alert">
                    {{message}}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endif %}
        {% endfor %}
{% endif %}

templates/commons/paginator.html
<nav aria-label="...">
    <ul class="pagination align-items-center">
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a href="?page=1" class="page-link">first</a>
            </li>

            <li class="page-item">
                <a href="?page={{ page_obj.previous_page_number }}" class="page-link">previous</a>
            </li>

        {% endif %}
        <span class="page-item active mx-2">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

        {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">next</a></li>
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">last</a>
            </li>

        {% endif %}
    </ul>
</nav>

templates/commons/post_card.html
{% load humanize %}

<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">{{ post.title }}</h5>
    <h6 class="card-subtitle mb-2 text-body-secondary">Created by {{ post.author|capfirst}}, {{ post.created_at|naturalday }} </h6>
    <p class="card-text">{{ post.content | truncatechars:36 }}</p>
      {% if user.is_authenticated %}
        <a href="{% url 'posts:delete' post.id %}" class="card-link">Delete</a>
        <a href="{% url 'posts:update' post.id %}" class="card-link">Edit</a>
      {% endif %}

      <a href="{% url 'posts:details' post.id %}" class="card-link">View</a>
  </div>
</div>

<p>
</p>

templates/commons/post_form.html
{% if user.is_authenticated %}
    <form method="post" class="border rounded p-4" class="" action="
    {% if post %} {% url 'posts:update' post.id %} {% else %} {% url 'posts:create' %} {% endif %}">
        <h4 class="text-primary">
            {% if post %} Edit {{ post.title }} {% else %} Create Article {% endif %}
        </h4>
        {% csrf_token %}
        <div class="mb-3">
          <label for="title" class="form-label">Title</label>
          <input type="text" class="form-control" value="{% if post %} {{ post.title }} {% endif %}" name="title" id="title" placeholder="My awesome article">
        </div>
        <div class="mb-3">
          <label for="content" class="form-label">Post Body</label>
          <textarea class="form-control" id="content" name="content" rows="3">{% if post %} {{ post.content }} {% endif %}</textarea>
        </div>
        <input type="submit" class="btn btn-primary" value="Save">
        {% if post %}
            <a href="{% url 'posts:index' %}" class="btn btn-secondary">Cancel</a>
        {% else %}
            <input type="reset" class="btn btn-secondary" value="Cancel">
        {% endif %}
    </form>
{% endif %}

templates/commons/product_card.html
<div class="card" style="width: 18rem;">
 {% if product.image %}
    <img style="height: 200px; " src="{{ product.image.url }}" class="card-img-top" alt="...">
 {% endif %}
  <div class="card-body">
    <h5 class="card-title">{{ product.name }}</h5>
    <p class="card-text">{{ product.description }}</p>
    <a href="{% url 'products:details' product.id %}" class="btn btn-info">Details</a>
    <a href="{% url 'products:update_product' product.id %}" class="btn btn-primary">Edit</a>
    <a href="{% url 'products:delete_product' product.id %}" class="btn btn-danger">Delete</a>
  </div>
</div>